name: sumo
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.5.4=h5503f6c_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=h6cefb37_0_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - black==25.9.0
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dotenv==0.9.9
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - grpcio==1.75.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.3
      - pathspec==0.12.1
      - pillow==11.3.0
      - platformdirs==4.5.0
      - protobuf==6.32.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytokens==0.1.10
      - pytz==2025.2
      - pyyaml==6.0.3
      - ruff==0.14.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - sumolib==1.24.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tomli==2.3.0
      - torch==2.8.0
      - tqdm==4.67.1
      - traci==1.24.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - werkzeug==3.1.3
prefix: /opt/miniconda3/envs/sumo
